_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.11.12
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 41
                - 49
                - 51
                - 53
                - 55
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 41
                - 49
                - 51
                - 53
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.11.12
            "5": 0.19.10
            "6": 4.51.3
            "8":
                - 5
            "12": 0.19.10
            "13": darwin-arm64
