wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.2
    framework: huggingface
    huggingface_version: 4.29.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704755539.786841
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      3:
      - 13
      - 23
      4: 3.10.12
      5: 0.15.2
      6: 4.29.2
      8:
      - 5
